#!/usr/bin/env python3
"""
03_compare.py
-------------

Compare a reproduced anatomical-space NIfTI volume with a ground-truth
*_Warped-to-Anat.nii.gz image using voxel-wise similarity metrics.

The two images should be defined on the same spatial grid:
- Same image shape
- Same or nearly identical affine matrix

The comparison is calculated only over the union of non-zero voxels.
This avoids artificially high correlation caused by a large background
area containing zeros in both images.

Interpretation:
- Pearson r >= 0.999 and NRMSE close to 0:
  Nearly exact reproduction; the source volume, transform chain,
  transform order, and interpolation are likely correct.

- High Pearson r but not close to 1:
  The correct volume may have been used, but interpolation settings
  or transformation order may differ slightly.

- Low or negative Pearson r:
  The wrong source volume, wrong transform chain, or wrong transform
  order may have been used.

Usage:
    python 03_compare.py reproduced.nii.gz ground_truth_Warped-to-Anat.nii.gz
"""

# Import sys for reading command-line arguments.
import sys

# Import NumPy for numerical calculations and array operations.
import numpy as np

# Import NiBabel for loading NIfTI medical-image files.
import nibabel as nib


def compare(reproduced_path, truth_path):
    """
    Compare a reproduced NIfTI image with a ground-truth NIfTI image.

    Parameters
    ----------
    reproduced_path : str
        Path to the reproduced image generated by the registration pipeline.
    truth_path : str
        Path to the known ground-truth warped image.

    Returns
    -------
    tuple
        Pearson correlation coefficient, RMSE, and normalized RMSE.
    """

    # Load the reproduced image.
    a = nib.load(reproduced_path)

    # Load the ground-truth image.
    b = nib.load(truth_path)

    # Check that both images have exactly the same voxel dimensions.
    if a.shape != b.shape:
        raise ValueError(
            f"Shape mismatch: reproduced image {a.shape} vs ground truth {b.shape}"
        )

    # Check whether both images use approximately the same spatial affine matrix.
    # The affine matrix maps voxel coordinates to real-world spatial coordinates.
    if not np.allclose(a.affine, b.affine, atol=1e-3):
        print("WARNING: Affine matrices differ. Are both images on the same reference grid?")

    # Load image intensity values as float64 and flatten each 3D image into a vector.
    x = a.get_fdata(dtype=np.float64).ravel()
    y = b.get_fdata(dtype=np.float64).ravel()

    # Retain only positions where both images contain valid finite numbers.
    # This excludes NaN and infinity values from the analysis.
    m = np.isfinite(x) & np.isfinite(y)
    x = x[m]
    y = y[m]

    # Define the comparison mask as voxels where at least one image is non-zero.
    # This removes shared zero-valued background voxels from the comparison.
    supp = (x != 0) | (y != 0)
    xs = x[supp]
    ys = y[supp]

    # Stop the program if no meaningful voxels remain after masking.
    if xs.size == 0:
        raise ValueError("No valid non-zero voxels are available for comparison.")

    # Calculate the Pearson correlation coefficient between voxel intensities.
    # A value close to 1 indicates highly similar spatial intensity patterns.
    r = float(np.corrcoef(xs, ys)[0, 1])

    # Calculate Root Mean Squared Error.
    # Lower RMSE indicates smaller intensity differences between the images.
    rmse = float(np.sqrt(np.mean((xs - ys) ** 2)))

    # Calculate normalized RMSE using the intensity range of the ground-truth image.
    # The small value prevents division by zero if the intensity range is zero.
    nrmse = rmse / (ys.max() - ys.min() + 1e-12)

    # Print the number of voxels included in the comparison.
    print(f"Voxels compared (non-zero support): {int(supp.sum())}")

    # Print Pearson correlation with six decimal places.
    print(f"Pearson r : {r:.6f}")

    # Print RMSE with six decimal places.
    print(f"RMSE      : {rmse:.6f}")

    # Print normalized RMSE with six decimal places.
    print(f"NRMSE     : {nrmse:.6f}")

    # Return the calculated metrics for optional later use.
    return r, rmse, nrmse


# Execute this block only when the script is run directly from the terminal.
if __name__ == "__main__":

    # Require exactly two user inputs:
    # 1. Reproduced image path
    # 2. Ground-truth image path
    if len(sys.argv) != 3:

        # Print the script documentation and usage instructions.
        print(__doc__)

        # Exit with status code 1 to indicate incorrect usage.
        sys.exit(1)

    # Compare the two NIfTI files supplied through the command line.
    compare(sys.argv[1], sys.argv[2])